replicaCount: 1
image:
  repository: ghcr.io/readerofvillage/cloud-api
  tag: 6da90b8e3b4717005171ce0bf6a725f7b22c688b
secretName: cloud-api-secret
secretNameS3: s3-secret
containerPort: 8000
service:
  port: 8000
  targetPort: 8000
  type: ClusterIP
envFrom:
  - secretRef:
      name: cloud-api-secret
  - secretRef:
      name: s3-secret
volumes:
  - name: tls
    secret:
      secretName: cloud-tls
  - name: config
    configMap:
      name: app-config
  - name: postgres-data
    persistentVolumeClaim:
      claimName: postgres-pvc
ingress:
  enabled: true
  className: nginx
  host: api.dev.internal
  tls:
    enabled: false
  path: /
