replicaCount: 2
image:
  repository: ghcr.io/readerofvillage/cloud-api
  tag: 84a777c1d94a67f8919abc9029ff70beddef6edd
secretName: cloud-api-secret
secretNameMinio: minio-app-credentials
containerPort: 8000
service:
  port: 8000
  targetPort: 8000
  type: ClusterIP
envFrom:
  - secretRef:
      name: cloud-api-secret
volumes:
  - name: tls
    secret:
      secretName: cloud-tls
  - name: config
    configMap:
      name: app-config
  - name: postgres-data
    persistentVolumeClaim:
      claimName: postgres-pvc
  - name: minio-data
    persistentVolumeClaim:
      claimName: minio-pvc
ingress:
  enabled: true
  className: nginx
  host: storageproject.duckdns.org
  tls:
    enabled: true
    secretName: cloud-tls
  path: /
database:
  url: postgresql://app:app@postgres:5432/storage
