apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:16

          env:
            - name: POSTGRES_USER
              value: app

            - name: POSTGRES_PASSWORD
              value: app

            - name: POSTGRES_DB
              value: storage

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata  

          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data/pgdata

      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc