---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-api-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgCnpmbB0JOyWTaAs+87mcFOlSgNnx04NxsFVKMy203Z7QYw4swHMsKrE5Ugj/MCSEcHn0PsbEyyMwN7ri4DDV57vBxrlVXSVXdSUya+FclbuzoMeQHht9bTdx/Rs00H1ugCyDNpnYWBQluR46vSUKG2QRRsQaotW/RgklW7YXGPRHomPMQBTuxEEEX45ipfrhpVcs+y6Gw46pyMzuzntVrulPRcO7Av+bf1rRc3osq/EPO09XhafuEm99TmvI+XW6MpaM3QXtYwAvHx6uIkI+uOPoNkjExq69Sta1X2gP0SevORNIbFoiSBmWFqYQS5AZ/azRfbSWZIqJe/kwgaE8rkWXuNpuzZapltB0EB99pARyTnjfTY6VsalSEP3+MMQKWRahMn13DZw7DQ32PZam0F19u47rQFJABsJrh1my9OEDgjdGFjmHAzAkXny1EnWVGzAjLAvLFpI6kjJjW1A8ItsUICIY2Tqjq1wMROuBUvMy/ngZVdfoarkP2vJFNtPdYCFRr5fm1BIjNYnalU6mgaYLiVHuVDBAY6d+eK2elrPiLQwjy7oimcJ4yy4QYxAVxwnlwMFq9JnaJ+OYS7XxjpVgu7pozv+pP+bN9Zq5TrG2SX+IYQJcjg0l8fHDXwjMay4KBrv0e+kFdaWIXhvcBcUoVbKKLoQzRU3/Z8EtHExvT5NTdHGypEZmxIr6gk/GIs/rH/C80QpVOeXVBaUwTOpSn/xUv0+z5mwfsrlyn4FgW/6Y1/qkrouXA=
  template:
    metadata:
      creationTimestamp: null
      name: cloud-api-secret
      namespace: default
    type: Opaque
