---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-api-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgA5mGjEuYas/hgwHx+sk8gjyHo5ykNDxYwZ7vXd25SpmOxdqYVNgwxh94uMC4UPAXcOeaFyeHaCuK4kOpv2fJWD7zppLrW82YyGNUhiv9GBkvZkK/oPiLU/tTwjhNAyTmDAsJPFAvpKRblDTDCVTvaz58Q00XCsbdg4tWlBSnbL9uc2fThBRNJV8t7qVUL00m4hRhtSI4EE9CtLOSrE+sUS487k9vwckEehkfJuDbSAjqoqvG2rcStVreVTtnFaTAD5c9piN+CHdBpWF2p1/Rnkd+Um5IkQBY91Rtzxi41NX/mk0y1zNx6bFnT4ucey89dBO3oiaiqCCw10Asoha6EWNjky2W9Zq/0RpJC5iICmkvb9zM1RKpIhomBKd+dzS7z8cBcUN+HnqAdS4mCXEwpXBhoZmli9Brl55tWZaiKGYqijYnttbFQQKM/T26vv3ylAa+PuK1HDjKpTtX5yg75JsKclhaMgYpvduf1xtt7POZqEadMbk1SOh7Iire+3vISwFQR71ti3TPxuqUTrRmFjXU/iW7LKI5FwYYDOn6w5M3COAQ+Ci3tIwKS1/3hoHH+XVsvPmJdy5sVxcSgjCKWeCAqizIhNFrC04UMOBeAlCU63J9jABE179ge9MNltmPHGaJPmanKT7INsTuJqGsK/nSCFhDl644j1E6pnBd7vD2Uzmpb6fsY1bprBn9JQ+ZrvfBHXnFp437I1tXOJttEGbDmpovsquMsKoEn1U92DJitR3Wlpnqoyo4k=
  template:
    metadata:
      creationTimestamp: null
      name: cloud-api-secret
      namespace: default
    type: Opaque
