---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-api-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgBNxFJ7++IZvPpNTHdxxh+7f0Q0IUQYXvhmT/s3JvHkA2yLIeaYDSZ42Tij6cZIW6uV1PtITZqKhjSlai5umSWL8fvx8IRr8YaBpqyEx2HetMxu3CNX/U9Hl0QBSWxrET31+pobPLXmfPxtJ1kWvKj1Lfd5ZmwfLponQI85j7LGRIUTC0+0e3YnPyo8i4HS9hZ4tSUVFrit+zqwxSJElO+REmPuqnlLDuZS6gfQ9TUZ6wSl3xeArA2/FUE2iI5I82u/Ap71jtD0WsWA/NJ8jEK1knpS7Nemg2q7FfMLFFxzIox2o3fXm1pAhraL1uTG5GjM5FW63apudUhaGkpT/7z3YYhDuAOHvR7ZBsQQ/2REx4rmKZ9Vznn2RKyeNKbXvEC45my4+MFfzwESOxNZoJozCUwFXKlimZDvyltAWTt+kIeRBMfE8GS6WCguZ3w1vm+lo7iU+8PbKZK0y7RoLf3ZOZSTmg75Sgwy511woYGMvDNeyNAP5jyAW/Ypk2iKD6UB0uLKoP5v2WWY8lTimfWwC7oyjJHKsY3Yux3081kdhbdlyZlLwohWIkW8L8jLp3tOaoKK2Gy0cwpusaJV2EO13pFkt7w331ZuPBb3kU3bMvsYCxpuTJVgiwvkiH66lULTTcAzyHjbaWCdabt/22iHe15sMbAH0pXPdaHVZugqkaHNdZ+Oqr1A+fsWJztO4agtAt9rEfwGVKlEYAaC9+m90HHMXwPDhaMJGb/G7Q9WpmzoCZwiNw37xFM=
  template:
    metadata:
      creationTimestamp: null
      name: cloud-api-secret
      namespace: default
    type: Opaque
