---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAeSB7T8WMWgSRPrOXFwlX2W/QPC7jqCxbCP/YYqUpUzI23q6eFvTX1zoPVmeIcmrU1XRo67TBwJimILEvkNhwUQAZGCaZFsOXjDojMBdiqojWlDI8getrnuG3vO+A618gBIl9rQOaTseU/s7FjHHQditiwYorRFUpATH301HNaT2aOU4IYGXaa4Irje9mrW143s0BTrV8UhETIr+2/NDg6kJDijMQdVWzFL1ZGzKIYwdsOtjK6os3aV7RDFV7OvW8AYN+PrmSzKrfwc5u9lWJaulkroe+lTC+uLo0FJUsZcXhuJtdFhVQ1TutDznd8E8jztC3yalPpWno80cr8AmDQaLOcp08SRx5bOviEkqRdsc+mSvPD9lZPP1KKAnOZL9XffNvRHuNzA1uUpYDZ4QbXIhY/4NvA9VduDlpU5p8jUK4PSpkMYqTl/0qbram0auYSvwf8NGjpNGjHdmHL0p/YJvsa0+4Yu1Lr1zYik/P/ecAi3JMPh2sQJLvSySDiv7UsC72zBnc1co21CYqtVI/WIF2q1sZBo3s6y9LEdHNXUTEO2yfm/m4p2NK7GYYCf7djYoYLgCD9CaQUPMjjHDOtJ2dYRf2Qgr3tSOIOe2TXNY2oGgjDXBanrwZm5tkqDCuPufgOhN42gS7rNw3KJW0WXRc5+dRZtryRhpt6y2aPrMDZi/RXnva/nVVBZGnAAa6onVWP0vV3Xd1L1LKcqGS5j3P7N/edAmETCR5VRdqHNsfwSeEp7KMdf7qxh1voGhe2ZZfYKI2Xgv1ia11eFXYzx7drcK/C+GzTKUNNzwUd/ZaYN/CeotPCORCCF716q3afSosX2iuCURSqkQT8oOvdcgBM40deFsibzyluweCaDDMNBU+ddT0PCBAGnXhfDKHlh2J0o9r1pnZm4GategGcm/hgQmJbA3ujz5KblcdixO5p5/XPrzzQZFByCEuluHFQ5/9Ho/c4dL0DWl2rtxNnIhynZir3FcE/pj1+zrFsO0oFk17JO2cn0BftNg==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
