---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAuW/HtfbWe+m2+PEIiXG7wJP/YLIPlN4Vr6WIsmFDvXzkURKkNRFO0P6On8XxNUo4YzqF3c8SqPX6opjDyWkT0HEeKK2tQSfgolKN4PG/CgnNInVBLEHgQllsorNJ6Z/wa819V+A21sYQ/7MAsXtz2XQRtYiWfuQkQvuzS1GgHcH5PwxVmhOAhf6BcKDtLc0q7mQtBHh/Yp0ONlYFRHXK0azMwadm0ocPkAFPFh5sBfY9DBdqfV4uBcP3vKYe1/OLaTkw2eOk3wiWep0ZSO9EhC8ZCN3h3Drb7k3oyiJeulgCXZ4SxuWYvJgmNfc/V8gxdyG1zQt6kSGigiRtYz8PuAovTrqcYWgE+v5gZidmXbC5MeAk7YoWIoVXagPqXlWWF7nwkEVjPL/dBFekOvD+xWaee1JRsmNyAPTRYjDHo5TpEWrBgU8XOh7TjIsRM5lS9cAyIjJcVwIrmWnI2qpHj03G75maxVI1vUhnj4d8FJTZLpUDSj0Jh/y9K6rChtuuG3mETsbXio/uyEdU3byfeU9VEh843VzEaHkqxgCtcsrZJ2VBkHvibdHR5KiUCcH2u5CRJMPA8Da835N+lnwlpPa18vDkoegjc9sM1wKiWGAJYhRt+UWP/yAiKQmJiamtdoOma0P7SZnL5+pgiNQNmlwreXlXNiZFrTBv7HGEVhE2xy6YZHitiQT8nF2cbroHm+EsZgeXqQBlPf3bOjJMnwNPOvB2ojEBc+ovqWMCu6tfqlndUn0hkEre+Y7r7swy0l1Ao19fZtIizur1/qmfqhGxFInyYvGC33QGLN6USn5gRHzkOLuPwdLROrT4FWWTVC5fdGs9m4gcyBwhGQYwQEnSNoRYbfTyU/5yQJVY1g0omDMf6NDU8n+Ly2RncjXqQZeoTK736Og3L4+YqOHlmRg4LiXOqN2Kurv5dGt0WlG+LrWmOggE2IrQzmpVVp5VZ9bmzIqtQjl8MNRRofJ8WxPsXH7FI2BPjabm+hEO4jXArtYthwV95kPUylg==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
