---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgA9XSVGcX3LzZMtHq4NmN6dwWmeNEPMg7DdVaBJXbyOkOQxp8BDnkunQpm0/Id+BKRgQ7XKut1RGrT+6baICpGDzG8xQc2aPRtmbw4LSB/u0HjKUrXsF4NNvVRBlTOFrHmorMohMNpB5nI9OSppFCpgxH8sQTHkgd1SePmcxugiZoi4/MleLUfasz2NbRYDtpbvqphEo9NhFRJURRoguy4Uc8fzU9fJam+wJ2mabZMzstGNjggXzWrm3exRIuCqviBGhjfXRG+qN0RnVed2p8i33tGdmLljJNlhCppds45Kosah2n7OdvueywsSj/DV0offsTKXQrPY3S3yzbguIdIzn+2sN5mKTV3AI9kTqjvXZAg+dRKUbsAjDQgbhXsEhELzzNWXl2J+lYGzofG8Rm7DdtMmCqd1KBRMywp2STzlMAuMaeBHB+JyyOcuxZOQxxZUzubX9yppgDLwwHfhQ3POZiHs068LcqqlRUIzIULQUElnK/LDKIqmDX+74ZCAQrUzYdwKO2ZCiiE5Ax0fAHS2jO2JZpmgK86w2bVpt3YMKCmqb+Ht3Ixsjf8dSwQgNw44HI5BzPzjVdCNoWMQ+wyk7CT9dJJwb7xjfuj6bbFyvE4ehqm40PgcWq4eb7M+N9uDVaP7GqTiXxPX4uuVwQiTcbi8QxzQ4VtYvSkL/6A87r6Uyn9xgTOcVo5cG/kHTvbWTsa1aHxMEMsSUwdbd3qIBduCXv3j/oswVgTM/m7D4x8EU07Z3NcRitq31u2xNyTT0Swb7EVAgs/EokIcQ3zoPhARdeXLDNVtpE6AEQdfH0PZjeLRM29PhgjSz5q96JYLlIajA+846GU08GNZla+lB0RhpmPMTjag1KtFVOdKZMwly21LgN7H3bc1rmAX2cbSKPJikx1LVoYl1A/viPYq1O5tmMx/iY7RD6eb016gLSmVxPs+yDZ/o9loM8Zb5TAoT0oIOrvon6LTMPq/TElV3ULQXFa/SeI0xGjRx/KW2O43w+CPlPLvdXgyUw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
