---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgBW8LZdkYrTP3aObsIERHnoBaXZvXOOkEu10yUEoDbpiE/Zrccp+mtlOyXfvklUPtMCnhGICW0toag5cLjigRj7Tm9ZR4R+ZrjubUYYurbWDa/6qop4xpw3tJ5HfGkREbThtotq6IoPXCS6LLotlBeGrQVSk7nFO9BYx3B5VaQwgNVVihJgLaXV6rX0ksjrVQNtZJneiFS4Qvlyr9ewDvEmjBy2DjHGoLcudVHYgsl2ZuFkRW64exlNKEuC9ERYpzOsvgeTIALsbzelVROX3K3pNA7wK3z57DIRlSEkCTMzMGVNN9vZ0XwvbR6yO5jxw4SD+pQCC6WxZPEkzHn1yO+esmLl5lrec1DNhTznjybease565p/msyx3fx0r+g5upgIxZE+rE012UqLsdBCXyHRVavlhN0/aThYvhYYq0vze7CITDLmuncCLxL8mo3sNZJ9E9LrizIaNvcL3blgpCYJdyvOughGRzoFt5Ml85zO5TALmJ68xC+YpTosgijqmpDKayqSMYfZVXXNRJOJ8A4D5rXvAXyRyPRznxqSmakxxSySeV0bFqgsgQ3+RWMxYZiTYWv/vamnjEtgs9f9p+tvzKJADgiAcTnBschYM9daralSQP4t2X8ZfO7SJmmu1Q5Lh6Wr76ZGa+0r2UTfKDIOmOzt6sOi/WzTx02Pg/RxFluiddGHaHvuICc++U8kbGNyoAToIeIZ2nm+xec4+40xb39YUXkKWG/bhzmRT5h6jBuDTN5rIflloi/cTsJC
  template:
    metadata:
      creationTimestamp: null
      name: grafana-telegram
      namespace: monitoring
    type: Opaque
