---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgAyr4yvBAQg7TGEKHR/u4P4JAcU+e+W/u68Bff6DnBdM8jUXoTEVyQVJaMKM4JbfAItj2lnV+/MDCnhHK8oV34989SgQI20uTUclB+Cpt97j9V2cqEeaeTq2MONI4nO/sYSdhH8fWP6h0zLERSYrz6FKwNhoLZp2qz/7qSnosrehUieQmufz7xOl5G9roKcjtlNYxbuB00rWvG4hanm9cxXmcx7r52ex6FPKpzsSDJhZ2Qkq8pXnHZp1nj+Z9Hxy9ou9sMQ23KyCHLxqfkIpQDGjSy+hNmHgnScIDa8HbA3zaB6OAFu7m1flETuFJjuKjByM1qccnCFwE05VgYRpFwRx3Mnp9Ynnp/eOuT8tLdsYY/FNSHpcjkXBhbxIl1GiPh9+nUPXKz+DwuGM6oRanjTwLrx6h795+dAiYQ2YkEfYU740Ro2aihTlpGt9zpBnjL/GzG4ItAuX/hkP6z8v6UPPpD8vvQ/MVHH331C+2AMZp8yqEp6fnMPp9AkYyZelV/vffJb5XV2xZRJJfR7ueB+lhLi/Oq72E999y9Ltf8KVjrzSVGb33n/S99uSfhcn9LI0wMY8QwZhyGwbIhV0Oh7Q7tLeKmJfj/Y2XGIR7zp5dod4NzXABq/ZeR9ylExNWdnDBLDfREJ1Wqla8awKWCat/mt7I8u/q69s3ZX/NUCIHIOWGJz69VEC8gBhVtrH13nswknUvnsrHs5CLiOIqzHay7X+XghwbXEKg2xuwJ6bUHaHR6TXvD0Fv/guVl7
  template:
    metadata:
      creationTimestamp: null
      name: grafana-telegram
      namespace: monitoring
    type: Opaque
