---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgAKnReRiws26P+Y924Bu3qDvGshakFAg+1x0z0/FC/6qxSNDa/ukoXSLrx3Cf7Ux997/PoEDcZtPBGnWlVj2lpims7vXKmz/G8FbwFkfC/tFbPBEK8CIupoztrTZaOqlSpZfLt3P3OZpc8et8QIPJeybCuDUD63SYSfCMMcROzKilTstlKyALmK0lYIDuDygmG56REXmwC5OK5ze1Vv41qB8v2GEaymSfl23upeseB+KzWeFO0sPW7woFKFNJzea9w/9Ff6G+ocrnRwWtGI27d3u5QrTESEqmbO6DGTHMqXSWxjqxH43VwrNHt3Wji3bHVAxdbFkmq/8EEDyTrQGjHq5LW8ZIQM+pJMe7NJ31AVvRr8dVUKMn3xJwBBab3yY6yGPUBnn8Vs96wtJPaI/HRNaiM8LCM4PAa3aTJl9/c+HpyP+ggIheAMlfu4/0uXKe1n2sFEnai2T56yBrA7vRIhVHVIuTYdA7iSu1H1BBaalO+lgTErf1bpM98uneS8QHA+f0KrFE0nYtOecz8qRMi+BMszXAm68W9NJRHusnkn74yEXC/Sv0QgAs5ZKYoEtDVzw22mXwMU1gA1Ft7sC2Nz1OsHCL3Cy9VLjRNLuR2OpAxYx0F/Rk/9zeza3/cCoxWQAQjCD4e/v/jpgEh3UnkhF99mQqfzU4a4zl6FcATbqoMQcm+8DjzsBRjvSXuHaEJlYlVUZkpUxODkQUTpQbDZszeJusBgoVdQGf1uuS+9Bi/tl4RdmXKEMx6cnax4
  template:
    metadata:
      creationTimestamp: null
      name: grafana-telegram
      namespace: monitoring
    type: Opaque
