---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBwsMaLVYlT2bSwOL2z+TNT6CkuHb+TyX5DXeGFI11EwAi+8dL+X3V9xCkdK/nKWrFjBTISi3ydFqXROOpUuD0oEwADvkSCKdG9L21uIfItu6o0tbR264sI3N372PV1qLUjVAzlAkK41dxrR+GLUKrEoNqCugmt7t1mjWOGwmHXv3donG4Jjx/lf5vbDe90ja9XXgT/RaYHJhEcD0Na0Aq5A2cFfpWTsT1xOALLeRDtGWEZS+iuaDa4nRsqnE1fwMQj6zQw6tRevJlPf+ltkfOBEIf5jHJly2iqZbv6WEz4y+sjryjxoqjdC4FXLoPKzKjYU+N6RiFsy6qALwNrE6gvp/mc2RTvX+F4qpqD3qpe/wMPtVKbClD3JGgpjZEQ3sTqRwgVRKsGFOOJmrEa8A+h1HSV0oJ73kX5jvXO15csGmNWLkxYtt92rFy3a4Qv7UAOrIJPevG3Yu0xA1PCa+mVyDhTj4rbUbJydooLTTsrr7HMkZj6cxJCcYYTOakrkHJIQM+P95MRtxkZcOdp2wNmUASMXZOK0g8WIp7Wj3U9h/BrtlLt2HujuhozUt7JzQ0lHMp7dGAWgZmi/sgXhY+T2mAY7TCL9aZ91o8MZDqK2oDnSWpjcSY6WDWowVssJdDWp31h2gjypTG6a0oVjFJFid3FwVNgMmccR8DJMg8+XDJgozq2CKHVqwu1Cd2hqXhv3DAjzPoxiUGqVPBf
    admin-user: AgAIvAdtjBZShfZS+px+LdpXjo1Ym1My0wLAOJIiH1UIfH7XrDtDAqdKlXxx6vEpxCIA1ytrZmFLPCuRZt73iLFOQBp4o4xok1zO1k4QAckan7b5Wj7B+bwKAa/03tkBf9rKP4IoxluVAx8FgMoHZjBEb+yNaUPmMrM0f3XsUCOUUAXUoppH/7OfdwHRvkQGAjvRiBbhdH4gmvNQge2JtH0hsWGt08vvho1P8yyW5nLEiv00r/I+iFLHGAOrKdWN16XnseV3bt2soK762vbfcganLXyiOmXvs7npjetVFOuZaqJmDy2m37ZAN4keg+dBetRaVTh+HF4FnCBcTqUN6lJFFP4///CyHBY5q2zhwJYu8Pb4tONB+16CAA94xllvaubAPlPzam1GRfoC0T0pGMw7LVhr5qa0XUV2IgZ+QZ/PK/C77HvTMQKgQb/4RK5AxAZqv7LXB64VBGhxKXaDS8xXNJX0vg14xYplvQDWN+BDz588dplZ6le6zQkDhJOwgrLNrKsU2iDAttH/jVW2Y4sAqDeEvxoSb/ptV+BMYWs54//qxF+46ralCbDqTv5UcBV8G8WMatCinigSQkmf35SgP0SjWxERCln2dC2ODRNJmv9XRDJE0jQ2jBFoaPhcaHJbR2s/c263s7J7vS3qS0jLLj8j8zT7h4UZDMO3sOyu4vqsgbXl17h5U0jLBo6NBwhRopkp5Q==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
