---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBHYzV5aYYLlLneRXV8lnk5qAuR3Hw7Sl2e7qFAwlelLgk+r26ZglEyyjeoDj5Lnr5TDs9DC4tHmKHJt1FmiqJyPXp0IreF8POLS245/G/pGWoNZUNHXpkXxiFxY7RCanvpX3lvGRSbKm7S7SfzJaZLzyOPlLshyDWlny4Gq5fARSVCayyhFdXiPq5566jEbgJskrHocwGQw5h+PZxkTrz1EDQAWTa1gOse3ZYsCpV+Kv4o5YTv1Zo4kZaeMJBkjHz3V8B0ETLVSXTWy2O3jwuE3C7ZwWtL200QYE5JRygNFLCitUtkBXauBFOV7BlN4AxFgONsj25P1/zR6gEyKzgFKt/rsxRydyc6K3GD+7yprDT3TaWQZNc3X3y6gbgGolX1JjZ0E/WZ3mSn/WHjOyoRQHCnY30m5nNXCRdNE7327H4FVcVyiKw20rU8ADfCEwotFjiDjGctXmZo5LtOUNZjshxN4gB1NYXHNCjfgkoKEXgGTaAc3x0lvZsffaKM95MF/LDaoU5go8XuTpB7T06TiKdvLk0SnnzZaNQqG05yxnaHUNWCRyLh/dcx1s2iqj+gPb9c9fttqkNaSsGAYWoOB28phWKtATrPMnl7FF1MMrpxrtWqdk5GrJlKexenlpKcQ4cyjjUbIfieUzLlYC1Xo+sC4RtH48kZx2aEDjL0gUP/DitWtYiGv1iOUzu3Jz5PxIyab+ON6HtK8rgB
    admin-user: AgAq33o3n6g/9Lrd1OA/EiYpBg1UqVXaeXix2uE/zajXbGor86TPRSDH09shzMpagiI6h9LAVK56jXTluH09teu49V4Fdx1XiTjd+brHF+AhVcoWcm0nfuLty73gQqqSWkv+GMnAYHLq1Z7TegJKb9oID2Ci8ATng0vDMMlxXNperFBuYDtiicIWbdngzjGOUJQhJDUURzLCfkWr3Z8G/JKGsb8k6r1LSN3eAo93nhohPl0AMaHLODuj1L+bSxsdx4dYJWwyHsZt6ZAoEKH6cnRldWg3fyFirIhNCrAZLBeK82+i7bnGeYO00s7cCazo3zsXVtRTfnIg8D2fZMICLvLKJAaIwLRDGHrCwpu/fcHPxE1675503Lbe7scoZdpMEvUzRFCuLwtayhVyj6eqktmMXxZhl93ME6rXnU3DFQHMMOq63VulQmLURvHCYG7oGYLh2PaUsRuWeevgpYVA2ilTw27ELscE6bvujNLDDeoX8dQp6HufeN/WWiqdMOv0HJAfqQ1ikPWWVkfvK8/3AbglTRWlizZUsp72qtvtF27jR5b9Oe5vPqblTYUMuuDWC1cBatvUTB6W1BBQrav+e6BXKS640FH4sDaQ4dByXc82VoYIHagcLlCR1ygHkF9c8bWpbD9kNQC1cQNv8gdcGtmIFwyAJQFlvkFftUvuwGgkGI9G46YQ/Bfk8tMyc4fvIrH+ViJujQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
