---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBdstGcUDFPIagXgj6VwPXOxI70ze3Z7BkvTiES7GDp2JI2mh5Z8sFMEmO5frifG03S8ut4VxEq20/raW02QG4bb4e31/rQnieHyABihtt9oRhHLaxF5Sw1Fmm7ow1EIY1Lh72yhFIaD3azedlYMucEKnpKxltWhIYpaYuwFfEW0oy6UhtqeNMvi75PkI5Dt6d9OQWeKXvdJxKuJGIukxnpHUgiPzhBC5aO6X1LmDCxgExRC8Gu0xztDQUb8qRVjUR53VQPXY0IM7FnnkEcu8TniJy4yb0+17kJp/XiLOaQjJOCjeFPnHchyMphMl1DxMDjQSD1G9YbsNAAFrYbaTN6uU3zOtJbs2EeBnQizm1MtITe4tmbgBp7VIvb0AGla20jQrtHbb5Huak6KlO2LcAOCz57JCFfLu8sb0Wyf3f2T5Iz8H0E+cSsmLYy94wBg0KA9CewfcGVJ0SEuoXopO6IGCRMjcZ+z93SCnXLs0kwfxfP0Iu4xJjCiLaayzS0krrhblc/YbaOvb0kLeWBUCSTgShSXJUOJQU9h0zpokyXeA1C1BriB49ypCNudQNoHa3U4/WoX/DE+u8q4+2huNHXgZI2htg9y5ssC9JfcEdO3gnBOuYbhCerOx3YJCHMGJ+cIZBeE8WtpQd1pJc/frkdy4ds1IEUZ2Uwe6UWZWKsOgrMc55/LOl1+L9F/DAbBcAqP4sNpZ6syO6LIeAl
    admin-user: AgC+m/JTK5VXRbHo33GDwo/UUcV3RlhvL2iV0pEvsj/PlusGjhj/GyDLWZtmWVnlZz1b2HT8PvpsH3wp1DjvW5lX+nZFP5dr5EJNjpTDyPN1RZ6YE+dq4u4YOLsApKqDVmvRL58YxwmZteGfd10bvIZoNMqa+GuPI4k4y0tk7l7EOLT/HXctTCsr7U28TV+bbUIALrEpl2P3suvO8Jk9dCPL1QeWzg/kPp3FJVtCeFc0NAXNISB/1Jt2xaF+rPcxrS8pvCKjm/yZxoB/3d3fQVlDWjn/8RW8Qq4t+DN9MWLm7PZYQdSZrl/ejzjC6NJEcMMcocvIF2o1iQrG2Q79RAfku7x4xYCcdrC8s3t+0rzA8dVQ/dsElG6Ug5MAJWmhv6Qpgw3rzzgx7RE7zzOjP9hrQ61hF+PK1DjWHXLku/4eE+R6C1lm9YAnTwWlW+msKUeNJfdHqPUFKA4KtPEM8ftInf7AJ7/e8WNiJF5d9kvrkxAW50FwJorqBtpPasIEKG2MfdkvV1ZeYmDk2IZfcG8vTLCOnHHEXpC4gwA2bfqM8c9G0f4uqNbhui1/hHDW7R755T0bDRxTlzlikVNXaJ+zXpWDVsY6BLUJWx7lIwWdTULuXvNXdPIAKygfbheoS401zI/pkfVNRo4aLl5ROhuarSU2VZhBeAkYaKU9XL5AiqcyHQLXDA+6GXCzG6E4yVdY+/Pesg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
