apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-api
  template:
    metadata:
      labels:
        app: cloud-api
    spec:
      containers:
      - name: cloud-api
        image: ghcr.io/ReaderOfVillage/cloud-api:latest

        envFrom:
        - secretRef:
            name: cloud-api-secret

        ports:
        - containerPort: 8000