apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-api-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - cloud.local
    secretName: cloud-tls
  rules:
  - host: cloud.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloud-api
            port:
              number: 8000