apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-api

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: cloud-api

  template:
    metadata:
      labels:
        app: cloud-api

    spec:
      containers:
        - name: cloud-api

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
            - secretRef:
                name: {{ .Values.secretNameS3 }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}