apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "*" 
    helm:
      values: |
        grafana:
          admin:
            existingSecret: grafana-admin-secret
            userKey: admin-user
            passwordKey: admin-password
          envFromSecret: grafana-telegram        
          sidecar:
            datasources:
              enabled: true
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki.monitoring.svc.cluster.local:3100
              access: proxy
              isDefault: false
              jsonData:
                maxLines: 1000
          grafana.ini:                           
            unified_alerting:
              enabled: true
            alerting:
              enabled: false                     
          provisioning:                          
            alerting:
              contactpoints.yaml:
                apiVersion: 1
                contactPoints:
                  - orgId: 1
                    name: Telegram
                    receivers:
                      - uid: telegram-receiver
                        type: telegram
                        settings:
                          bottoken: $TELEGRAM_BOT_TOKEN
                          chatid: '1314692948'    # replace with your chat ID
                          message: |
                            {{ range .Alerts }}
                            🔴 *{{ .Labels.alertname }}*
                            {{ .Annotations.description }}
                            {{ end }}
              notificationpolicies.yaml:
                apiVersion: 1
                policies:
                  - orgId: 1
                    receiver: Telegram
                    group_wait: 30s
                    group_interval: 5m
                    repeat_interval: 4h
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true