apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "*" 
    helm:
      values: |
        grafana:
          admin:
            existingSecret: grafana-admin-secret
            userKey: admin-user
            passwordKey: admin-password
          sidecar:
            datasources:
              enabled: true
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki.monitoring.svc.cluster.local:3100
              access: proxy
              isDefault: false
              jsonData:
                maxLines: 1000
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true