apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registry:
      - name: ghcr
        api_url: https://ghcr.io
        prefix: ghcr.io
        ping: yes
        credentials: pullsecret:argocd/ghcr-secret