---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-api-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgAGJ7DrsVhTrI6kvHuHCqBVJR9O7MVi0VLpMcC6/4yqw1opC1bGqXXZQfrG40lJt1Ht0YPLUj/ODvk/qDlaXEr/EyPHMoPEUj1H2FBPSmdQYbgr0jBEpPm3DSNi6tTil4OlJtYdKFKqTjal9wxsF4DxcT5ODcm3p0HRMxz7bUGEOYnFCzEws9Y/AOHu45LJQ+b43zXmsUAS8XaLsCoxDfvXfGHYFo8gCPuG+2sKHo6Iy0XQRdftJ2N0fylxVfp9DkqjfJwQKzM37ZmiWgpaT/h8lxR56XJN2Xa5r//ppkik0KgnzQFR+ufNxNNfVAoF6c3VkG8MgjW0tY8cl+df5e7jL8AaWYp4MLH3JF1A3n7USw3zBzSOnpXF9F6mYnVWbhqHJbFM2M0Kdvr5GLmSKukfHPfbmkGomm9nXgbkr29w5bkdlFw6euWdfMjGuZWLSmYX84ziTH2zeRyTUw90Sdp7VSyboE08+m3t19wNGHeKod9toH3F02V5sWq8wvWdjZPw2mqww+NQRIgRvcvgS5CvO9wcvO3ALfwrAtmw0DNfQ8MhN21ipK4PNOxbw/02jKeX4hrh//j8AYDZDAiPEM72ANeTEiap0PIUygUEJ/MKRERs31U+dCsSPnjvEVGpYH2FCnaUvpW5MRa+670uahdYcPgD926QI4wYA4ki9YLIaA7HG56rVCO8wLQsEgpjGEUk091K9Qv4afksG9xqfazFnF5tuz6pp7RuTihnSbucvTjYhp/PLij7UBg=
  template:
    metadata:
      creationTimestamp: null
      name: cloud-api-secret
      namespace: default
    type: Opaque
