---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-api-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgC0G8+8UBJf9UJlZZymFXVjlueUuasPaN/wBzD1dpjGSSESCC0doFCGs0wQBMuzszIzaJkw6vRWBt0tEn4Csveb2s0/xjw7ZUv19dUAChBSaTNZnDgWPDt2uINVoiN6Bt6ZZ8sPjXsXKlmoxACDJZegaTXB+Mzor6LiB4oS6NnfIxaVAvern72uzQRzuijJC8k1CtgFPHfmzsd8RwuICmiP9IHeLg2nrgS1SABj3yCdHqNMk55SJ0ZJbN+DwYNqPAhztUF8+RWEVt9jzDinqlcb/dOeAEaTVIdi4UO7sZ3rrESNw5vM6usrTxAcrpBmps2fwB2yrGkGu9jIlVSRAJXQlj4Cq456UeLsFq7S48fTS5PxhoBd6caMTPAMNHfaaaikHOm33hMaf4g9hjwGFR8YlympKFJ3DHYRy6JJhjd4bwPC1x8OeVOPH7kYwg4XSJ2D9z6CTWJRTzJ3Z0nqjAbshJfpQ4CBJ3RiPK+HGaaCa8/D63wYf05IbnzLdVnUDpSWQ0Ej8H7125KNOD9NWhYOZLxmrmIiVfIEeIVV/nVSYbS+546GwPmCdPS/f3Hi7IYjpiIW2hXl2FR0bVx0b7GNo22kNQRPpanTiqaXAXWni43kSa9nioXeiHIdlPtDkVjelyEURcom/qOoTyASTLG+0MlqSTQc7kh6xVgY2W46YiDq5X5o86Q9SjGqgpaPjc+d65D4hHc2w8snm23tr6OgyA0savDiY4YpbOmN4SVKkfnG7atkokcsHIk=
  template:
    metadata:
      creationTimestamp: null
      name: cloud-api-secret
      namespace: default
    type: Opaque
