---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgCodwOs+iSoQi4YC6Wq9otUL2OHWDtNZZF+ME9YpDkhLdxpURRvfe8WLutvN12ybVkXe8ylundfDPO93Cvs98vMw0QwHCKZdJ89p/FZ8QWLQ8KtDjCH7KmVz5WMb4qD9dGBcgVBZVU055sKRQslDMLTA0OVc6Gv2YeHJxM33sxzXEHkQxZ4cig/AmkdBS5BJ66SZvsRAwX1xp70FXPrIwqH5b3BdrMGC6GM7E2Y5YbizYaq8JGD/YJZvSftbWJOqdxUOWQ2tAcTeDTcLbJxRPJ9ij1DUg7m09rKEuJouqnwH5hP9cXwW/PY0fyviY8MIa3vASTJD8bny+Hr9yyYpR0x/U+E0uhpyxhOnF0FU19UWULcZYJzsYLZPq56gq0OfYESO1RZU756u0Z6XX48uIaPf1CzQE7wHLUuKXD9+0dv+oI66soOWkFe1Yrf8+45obnUnujJtDP5ZwEYISgb7b2yjtf63Fbm+yUlRJN9uhuIzc6NAH4fsj6u3rhKV7K1D2EGmDFFBzdRX7pZdMHEgfFbJrY/00i1uBtXHAjWfZjqyG4sHAqMwqEcac5Y/K4gud9m5N4Bj/EaxHG7nRcJKgPkCld+kcv6FLNe8HXkJ8TrS4MJauBo+vLMDceqTPy2nKscYN3DOe0zIt1r5ShK5svUbdTqa+Zyo3yT905FyeV11T1MT6+uIaSSN/l4uXK/pb6hpMppN8hN0X4MG/MXasNrQcMujB2VoqsEmkaH1CEEfzToRsygtEjsd5mb30XzAnvrprTvLkGSbMWnERH86g5UARtaHxs0gn+oM36Dsk79ubdFwc/fvV2cvQa0/iIhWkXreaX3aG5iCuK1N4khOeGOAlpns8vsC/i/lR0j7flDrhWm2QWZHZY+MVPjpWZNcXvjcEpudn7mjbnG78vv+gQy58eoppgZnPcZCPKQR5askUgAswZ6nZNQXKl1TGlK6JDWFWa/Qu1ngI198Yf5Pd8DaW7sYRJTH3I5R1bETzBFDwxOMW+NZPZl4ppgQw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
