---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBHzJy7PtvBy3oSX7Nwxw7ZXPnXXe0A0f3synoqSvK5DBl2PEhUyvZX7Ng+VEP+YoOjen9Xbf3a+adyPNl+trbEBuaisXG/vzZMjedPyw1ABHpQ6VjrBuy3IfzBBDKXekur35ns7ARmrQhTTMLEY0EDtyVmL+ClpguyojQNCptveKz13tazi2gkBiUr3NFagTF3EoOFw9KjAHldP15t1qSkzuaSvl9HXE7KUopbBz2LZQyrpt0Jq6VdeQANt+xwsK6j7xDKLD3kB+HJq6cxxEira/uOosLlwG9oeVnQkvNhVWueiy4qnBE3HdF63HreW9W69qdqcMaD6bRwGKOWSOOwZFyNNG3o/7zVtHht62HUI8E5UNqSMLm40fUs0Vr8uq009POTKQ8LZwY9VqF5pPIpFYqckyJggzaKjW4xAbDH1OspcI0E/U/vMf/SBt33MYetzBnx+GSLAzkwIpKneOrXzj6EJS72jh277DetHT5HgRmCu7wD02/RtIZNeTB/j3kRuQGv+ezOfYszXuZ3n5FFQkWKUffQpPT3v94Hl8+rjCjA8pNwgLpFjGmXTHUtyS5o1Orm7xRYJlVs+YKgBPm9rbZ80sdvMl18JtikfK+qRa8r4vwDmOi8dz1M20viAzl4Wwhwa0gYEUp/ciNn5SINUzlsOM+NaSN/fNNrfQfmlqci8DPa7Ov5Xl5Z/ghJhyLZcl3/S9kmwbvx3nApQu9/uw5xWxvIK1iTU0QuePI5qX//VIdnEcGs1kGNkUAp9O6Y96YpvmUS+mGaXdJlsCvmJSMqy1JF+f4iKYGQk9dkPKYR7sI+qnV4TZOnS2aQ3rHoEkMTEbawkLHTgfPhUTSTeRkqbC5OMzs6tCgBcxNhfMZ+Cei5xS4mOuD+wANjN+i1KWCuwbAFEvndrsgDK2PlnqpfSHamG409SQQllwbYwXN84yZXw/ZVedrSE6QvrJ8FddYLtJ3SNUogHBD5oyGboA0Qc7hA5WELf5pfFQi0jgEMzapad3tvXds8kQ==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
