---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: default
spec:
  encryptedData:
    root-password: AgB7sj/CMYLHQUKu6x2EhCw2YsiZSPsJeBvuYKAUZ00HJH4G92b364yM+GQHfc5eFcVEWHdUgnsKWZX8BPIn+hZ0AGk4xzwx34vR3LGQ1aS4EdGgfURzNhR0qA39cWU/wO+TtBtHCjszX9w2t0jmY2Bz2vH2dDbsP556k7wi5rRZ7+5j0se55j1x4BKypA0sFYN1ghQ+CMWOELXj8rvUQrUf4Jh/btr3W5nxoAfC9tjkQu8AyQJQcA+GerVKb0dkTHiStvTu54nRPyNZW4pMfN1thAlrEJPkg0HNEFCxZALYj+u8Az3tgpGSWkXhAI5V/x7LJkdV4+Rxd3H9GIRK5I14eL3vUN1Hn706FbhBLWsemfvv2REDOrazP0y2N22BxdSMfZRwKVJum/o/JHQY/Yss2wCX5NrtdWVDsJMJqSXIx+gGm/fDak65e9jq7F0NWnDBhDLJWJiaGz5S2wGoSIkxdr7LtrOmfTC7oh22G+FrCW19WE+dAkvc3mNRlOqhXUnVwARucEfgae0g3BL9qAQDirZ4/4ZeWvSnqzGLwfSJ2YXzy9CMrkbll97FvfikWZUB2qmXHA9Zi6l0/8lEHslyaJ2I1ZKb4/qr6NgjBhOKrjU9tsfv30YufE1ab9jJ8j2A2RYveTimpezbwhMSyXelxy5Mie5sW2M3UeIWzDwyvezhYJm5l5AqfXKpGtKgf3D49WBdHdCytK96yw==
    root-user: AgBY0k/r78A77dS/ih++cDG+7K/QC6wwgCNT6N1nsK5Yg7kOwCoMM7lmBpQ05b0FTKRtGk9w+GTzwbyqE5SsTzb6YPumpIpqqDOP/tvDHF6KPXNyMOC2jCBhSWhO+t4fdffAUW1trKi9AMU65VUuhZdjz68d7t1DTt4Hpb9/qZz0VQxgS4qwQqGJhndKnqlxvFCNUYyu2tTDPuH5PwJx9JRj9tffvBnmyFnpHaVw2GmkvwlxRgSiA/QPb1FENBBlnBHtszjSeGiSoaT4NJt6lMB33QMcKg+0kNrm4GDB/O+d6AkK3699m5MFcDKSnqutVPri9+2vYB1/Riilh03wTDiSrIaitSZdORpt+ImFuqSGg7nRNG7YwLQm55yI6H/8AcEsrgW2t7fZ9Oewyrwj+TC7VAaONvOfmb3Q2C9dQZp9REukccIQJ+eUIXr6SVU+2ty6I1d7Pi19i0QaSXxxMgtNqhTdCIhN4We0DlpHwmPF8YnUIwNWqh8gTlSFrjKqMYxcLfRJ+/kfi0YG/C4CWA9dTBBX+IBCErTzO6of/XDd4ycNuiVco1jcl2QI0OQ/8Q5LTrUQAlty5j1I4lBn1ywS0ywLnu88pgZQwNK30ILdSLsN6y6BvLfVL5BeUrkda93YHb4OH4JgJHzc/nuSQN9vvQvH/NTM+nXdJejFGcCK05XkBn2ODAKHwMTh2AwcKACLBLFy9w==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: default
    type: Opaque
