---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: default
spec:
  encryptedData:
    root-password: AgAYMsy9gkHlZ8uzTkBMtFeUJdbE2sLkmreSwYlSSO0Xot0cbeSZI5fiumLCNNJIZTbw9S5CuWeNYNw2eacVrxCnfJpIksIfQHpuwOkZMq0VudVD9KUh5Wq6m03LLOV47itrbHQZfT7IITU/rIEJt6h3yUW87fvu1v0xuAmk7UVlxfL7jEh9WP0d4yXNaoSfca3UEpfLFFZ01hvwbQGSLKh+UQkxFhdylUIwDJ0kBdwSAeCuO52+/y3G6UzLutC/cyB1CEIa0kkBaXOpY5JsBc245F1IoI+BfWFLbAi4GXf4WGucb+SRJqaM8k9zPiqMPx+kBWTOyWJRuYCRfZaoVZTtmZnEJj7q6mVa8kSaZSlYczzVQjn5+Msf2TnIk9rTRhnywu0cWQSTzdjz5J5bf+FdXE34Di7Yal3JRLn95GWfiQXsEhuZTTsvrbKQWSwhcxRVMyYgHJw8JuZ3f5oKtAFX0Vb886ZfnYsGJm+jmbJD1tXX6NjDm6XITOIMdv/r/h2BKzkZcBcUeZB/SgJ0o520v+KlnPzgqqL0tbox2YpQgHJHu6/hu0oCbqvn6sk1hkmVjvvbrM+v2eqQA4xvjPp+yYJZB8kufF4zXFITSClcjiBD0k6xA1ZFZNruU1pfo3UYEC7wupKOp3IgpzAYZDMArQ5Y0ATHdlWoViT9PkVHSIgS1a1FzjE9YiJ6meu7134MIA8knzNKC6Q6uA==
    root-user: AgAfDTEVT5zvMIq83tvpuT7VRHNqJEVmKJNZms9iW6geTSmZgdbLQDsrHY1NPO3b6Ip96XrEfoZDsMzFaHCQkqWwEBBM7erHUOHjsj4ZlrDru/e2OdvN96M7RYMAIr7NE6qwQnaUatszFq4vo7QCTMtcnh1BHidOJv/4T0HEWs8qtNJRJxTdrhoRFRsWNUEQU9e5l/TZgkissWECuN+T8Lpi2voco1BSw0XORrfiGjF6rYseokr3uBTgcHo2YOHq6+vnywzvvOxxoGxun2MS0dJLg8NFFjJmR/f+9sAwOTiNjxYcRD+TPOf8XoYD1Y7qOEj4g50Ww2k1DPPdqWlcdafvoUdLGrbF4CItilOxG55xsNoZHEB1TblS1tdxUycTa3M5kxYUsZNoKGT/lOYyYivv6cgRRcHpe8Tr3Luffia9u18g5RQGj5gqRNM682gcM9dgytEH+sETjretdvNW7WxZi4khfGjHOWBH0tr7c6fq0qM9AefSXGdYdo8yVi8Lg7CRHvd3fBKqDBl9DJnGf5rZsvlDvuNrqleS9/SK4DV7ce24I6FBE1OcadTE+6IvM9L6XFKROSH1weDku5B13sq4dDx8hpGFWGnJFsjVrYhfx4ridNpg9NLJ9aquZ6VTNsMuzvqoY6F/tmaEKHCv6nMugkG7u+pm7L50L4CKAYLpF4EJLqMZeuMRaBqlo8VF0DDZH/YsRQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: default
    type: Opaque
