---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBfxADmu/cvKrX1sSHCKu7shxtwDZwPTSlkilxmms1WDMU6dvDYQY94rfUWAnrWAJKCPVP8hDoPYS0o40TqRJhKV0dPtKg0g9Oxqo3x/rN4H79d2hqHrSi8mL5shh1vOkBoBSCM21k3h8tkru4MZIH334OKWdaKKOZSY4KsYSjydiKu081ngSv5aB8B/GgIwY4TGv4icGC2ZUelNxudYiFsXLAWLxVJ7F+m/6SPDFPsAnKkAfN9IDGJPffTjaAEpyKVCERqz0JZAzpJADggu3xpXEI634C+7oPVhSOtTVH74HN3XhT5MzrcB5XoU+YCUa/UY7YnKCwJPDZ2oybAQEfIYn183Qu+xgr1MU8xzewVPEmmviYD0SxULveEJA62RdHDfkyr15XqHWN7MU0qud+Qp49RWo/yPPv7JAsF0+fil8a/5E2GO4oZC8wER9xtdWf2NYv6C6BIsq1QuIWmxlGaOJmAKvSiHt6OoYVUHQ2Jr1nX5Cs/NPLSpOSMWlzE+aocRFCkwwh6Ci1otXc3NZkWhRFtl0dGQ7OEn58YQxOdECZBXF3gZ9OLhkFbNX6ZNvKjaQyiYTThpME5m6b2fZ7TIODfrjYN2vq376nZ8DKq3ILStjA356qVW0nZb5H16URzBQVuPUUhk7W7G+/wFxToEVgdwbwOqPEy5OJzwLjI+Vec9pbphzV6sG+5xa2DZxmMyK473viN0o8QfT5Z
    admin-user: AgBYA3VxVWgU9TjQhdgPQx2F7hJ+UcITezBTJ5Uk0WZvqDeOrA/UoJ3P8RxK1UCC/oSUwaG1c9xdpiFVwEY4lg7rwyvLRxNdlEuJ79Qson346Q+JdT6DjwFiE/Fq5Qqc9Ob5kMv5dGY3KzhBND0rh11hwN3XMeIsRU7ZgQQxYitfi/ZPnMvzJQsNs7tYKhe88ofEuqy34sO8tCjeXZk9mLSsDjlukWlyddBEMqGJVvJzdZHxawNcV0MjxvRfBxMrt7QOerzquRGAHa/SwZJC6G14fiQGFq/wQ+Jg+KTj0L1//uyfPfYLuazABEJfl3xaO7G/b1xdp/rudGZh7o4C7ftnfCWv1JRwd3MFuHu+gTJsXIMJl2Ny14tHgLNA5Xx3ncuPm+jwJL2gCP0s79/lgZQLAVJPcpImVhawBZueWkYw/F86z+9jbR5NGjn0uBPUa0l6yti41gesodv7PZ6vHLnUVZcIs9QUXP6rMnWIDT5rIDBZqttmeLiFETqjY+KWjwfKJrDGPXzNpkTlzDVLXlS2aev2ncZ1UZRHZe9A3COzKr+uznC/gyWkrI4BD5HkIz3LRsywWd5Ocw5+Ds4S/QJq8HeUxZLH01GqhMudhy0bAAy4COFUrxxBFi6Q1FTqokAd6SuYQCcOZ8xyQvW8E/zNlzDQWMDSGplMoIJxzWD0TvFrtV076fH5onNNJtG6yc0wg5tIag==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
