---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgDF/2EiWffT2uOdzfNLYOKHbVMpE7FZS/sff80eAI5tN7UhccRUEwFFDX3CSXaOjhluk/Xs0+qRWTTVvBUIK+GTr10IWk8DSdFDEgMaonXdupumX+s9hi3UplFOyS0bj+qRXlmFyOS+Ig0wq2/8drL/cu43H/T8zAP7zxnjTxRPQ/uWrt5cRh0M9K1sSXGxfWbzswupGQAQliNVoWTNi8xL/rJV60FLnMa5J/rAq4xsmaHyu5RjydL/5bP5LEXjj2S88UlUlt1KmYeEKrTu2eZ4wO4qdocrRSIqgXzogc+uDDbEeUp07yvX2ti3z+U97PSwqqnZdGkBbkI2yKngj1gTwV0O1JPA96gcjCfQHyQYuBMGn+Rdr8Ai1jKNnUxwylR0+tKlpOER9kck3IbFdqLVB3UkQzG8MVVF6uWs5fZ36g1wXw9p9uLZ4R4xdVCAjnuF2eFn/aGZ4UZduE2ms3w0akQ3NTgkI07U1f7aPkvOhg7fTSeKQ3bxrWAfvZr9Qqcv8ftfUZ4FjrKYE54/cbigAduHQRYqT0cGdB28NQz1tH4RGv6HAwcQkoRRO+ckpFiBp+DgHWDOJ1E8bBO/kU9JL9INRfSNSIpr7Ss4lnhYt5/hbgxXhWsB/4YC587DsciaceSiCe5Ez7c8+IGHjQzlp/QgPZU8NlrufLRSR+xPtMB8gcxlBMrMw7rvMUu97U7BLdBPNGUHuxhsK62mSnMEot6zJ87rM+gdaxkjWeL1TIvJ8xagnIOukPyLKTm+SC/bZNHKX7/ysQ8Qtz12BBSRtASzDp8BIWs29feSnHozpatJS4b/F1dMqfdku1zNr5nPCSbI9YvM8yFF5zqrhvoGoZmf/uBwhz2E+jwdXUY3ePdf4Fo2SnqHeVgud58ckDquBMgDLGjOPZuTbRo8/S3pjQqEBvc68qD3CRmPEGuTJw0lJYPODWbiCs5YTwXj2OM6hnFS5r6vZ1qJ0QLdqeA5zEBzxy9RVgPn84AmOqdh7TQuiqTSZxwp+aMgew==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
