---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: default
spec:
  encryptedData:
    root-password: AgBVA3j28RNGyuenNNcT32IgA+US0JGl0YTijeZnu9ne+nfYy5RruEQhlLMkK8gv19HghHc5zHMFszr4L6Novj0XDHRIQU2IRudfmEdWi2eNU1pmlf5TcTvbjt4w9BRZXs+TvMR4WtV4sExPd9Dh62jcjgdwD7v40g8nfqjb0dcV1T634QEfaWhgcGSdTJuxZbs7rRXjIQQ2QdCdpz4/Tal2eD9rTk1am6naM6VWU2izFBqAp8EncisVxyDUU5T8FzlSsNIX1ziFXNr6PL5JtRfOlaoMueS4FoFG7DMU/mEQ2SRXnBLtTLDr/9oOZDs6x6xL80ucu4TjwkT6XbtgoO+DRfqqr8eHTdvypGRRVbxcCGr7T8zpiTq3Q03huYE4KgM8s2NSvYuHiX/0TXX5B65uXk9eV62jjwBsBFTNpzX9vfHa0d78/XiMRqgwKtBrFOw68goNhmdq9tkuzJ7t/9K30kI8lt6hAZLcL+TR7iSE7qF/3s5YPCfMt136saHYQudaKmde+Pa0nDiPjHlIRa4RVdtTewmxVvgNE1YBthtXKnuEvj7Ug3kaYtA1M9S/aZziyu+VQjiX0PJJet6B+Cryo67wdGYb0SxAlLKpTKKfH9BbB3hScpe25fWoNTxKmrbJUlmGlmKu2x9VOKwXtHwBoQJCq65LrKU3bZgjttrFhTTMU47GyhfZq9pvRokKXNBa1hyw7o/SEMBDVA==
    root-user: AgAdL2S8BfFQe4Kzm4zSdNxzB4izXmu96MzDMcETO3V4AA9WngYCbW6e/FaYR/T5zVFmTUXGewQZntQChOsH9OW2UGcA2J5KSqUhIenAP95EYVK/ErMMxDCxJ7rmHun53uxy1OXFmFR/7SZYkUEeGcNaPoMnlFiw0gnBPLRvihOJN0ovTW30aJifK1KmedN6Y1YcyAPve58iaDP8ECM4y9JedOpJgkLL23ShKr+xXNzEPEUZ1Mwnzy/PlgmUy1ohm30nAufsDRGDjIE7k+RpaNd+5YcqbmNkq/h8gtgtrWRuYHluge6aqutkhoY9xWRHXYW+CAt1TDOF0n6tG70CenwrjereNkGbYWzg3kVbmkKMso9bynivO8SmasH1L5xkzVE6m/HuRJFTit8EFLwVVH9VGR3B98oMXwC30StCGKOP7++eVnA3jJtb4yPU6PTXNpEgE2BY13rOtwmoKQ9/6/NYCbfMHh3IGJ/ls4uRftfoZq4jKBzcx4klKqXOMJ1PRz7eTTe/xOTeNB1pTSeVPjFv/rDTgQGayjb4DDqM2pZ4JAUrdfLqC2PsXUw1l2loP9Lxpo3CL5tp2OginDQuL/0n+k9rdLuXQ2KFO8jNoUvR7LimekLPtQmh1M53TQ48Vi0suXcdJ7WUOm/fBjO5QkI6rY5WWQXWFroLMhesoRQndOFLSRvJ4BNOI3pRLFfyR1sBIWQpoQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: default
    type: Opaque
