---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB8qOoMVTybl/h0EdmIKYteaxCeUH6QLT6LAJzJORWRoz+Aqi/R6Uqi42EutBykQAGNuvG5MnJU6+uXaLvSH4XpKsIdn6tDBuyRY27rnijaV0D3dUnVO+kLwTO1iZEYEiTK63/gcg1xm0xEfGrEhRvh6rQot8bCxM5kfW2ZisjFXO65PD5Zlbpf8gdTDNiO3l5VTYJo+foRYIoSX8G5E0CzcNIlrSNWrmRrV5jWxpmdxYQeGfxgsvychytFRioo1qN1SnBCOWzfVA8j5NEOA8hZ9BwOccO4VrZn98EiwV1RZkFMYpBLrk7BEIGI7VKYlRAr6TEuIOkcwFzAaABIyvDgWNn5HgUK8IBcWIOH6Cx6BqDqMR5BSyhfR96Gswu3U6JFmd0o8q5Yvi5ui1qDQ2Y5A9WSJbUgrOLYpMLdApzT8bXcoxXm2Tpr6Zc/sA040i38mEkPg+yNtN98eR6/IzJjELvLyHgy3J+hcLyAWuDYJDxQBlTKOg1aLjVO7SJOTeGbigpV6eAv7lTVyc2xXATLTssT2ohpKb+BJ4IiH4CTliFAmiUodTv4r1HaPDP8Iv7+1wEiYqtAiBEYQhTqnIWDTrdveWW6jN5O8990/S/Cufw96EXpgbZanUUHpvK9Xx9d7dIFPGS562RpIL/kPZprAqsAi6dx/h+t7afS86YMvKgO37ezro3f482TM7AKGMSZkXZOSCyn9Z0Ciz1j
    admin-user: AgCSuwh1u+Ly+48vX0nOy9B447pO0S+FJkUz4HN9YbvdYB1eK4eegLUV1q8XMXHAhNCpKytll/gNShyvQYv7CKEi2X8X4bXScZmz6J05ujtfu3biT2LhZztdSIz9lTwRoX0f7goteXbHJ1aOaxebiknLjQt8us2d2s1q7Gn3LqhJ5oVy4tM+80Jj0FlfzWMRYzDlPaW5+DHqCqkE122orTH/HPzamy0jVaFZFKPpHOEAm3lTVHCFJQhTgvHXZNMb7jVO1Bo+QIYkIebbHZfEdLwN57ehB3xWQJFKW6ojIVnKRLCXB20LdTMC1U8bfeejYxyJITaNKrqAY6KzzcaVEU2KRQ7pi7pQo4Vpoavg0IvEofRJShmkuH4khO9FRCenwvhUMxYJaZAZGA2uzG7gNM7dHINsX3WiXsE9nrRj/oYzeszFfbWSfFoxizL0vhNjbDmby/1P5MuzN+7E1jLyAWp/Qc1tOhAxnYMW/eH+V9wzysnbcwyVvxMwG0BqBRaCNNBPgOM9qsF+GnPn2iGcooqyb3Geloy2igY+BVGdO8/pR5w5r3MBuQRB6wGgXbhB2OMOvvNphg2gDpR+HtiGdrrr5d3Rb9tdVLQsqgWXWHrekaRuQRW/3s1YuF47XnDIv87LVxOAMoPNOWEMu0aCQ25e2/O/ZakTVnDDDL/4MGsOxvWZxwd5QvhKJaXWe7DILzGNCOVIhA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
